artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1nDCEIeVuksfmZi2vYb2m6BsMl6LmH6tP/view?usp=sharing
  local_data_file: artifacts/data_ingestion/Dataset.zip
  unzip_dir: artifacts/data_ingestion